import {analysePack} from './resourcepack.js';import {builtinTemplate,readTemplate} from './template.js';import {gunzip,parseNBT} from './nbt.js';import {generateWorld} from './world.js';
const $=id=>document.getElementById(id);let pack=null,template=builtinTemplate(),categoryConfig=null,report={};
let templates=[{name:'Item Frame · Simple',file:'templates/item_frame/template.nbt',preview:'templates_preview/item_frame/template.gif',kind:'item_frame',template:null},{name:'Item Frame · Ksepsp',file:'templates/item_frame/ksepsp_template.nbt',preview:'templates_preview/item_frame/ksepsp_template.gif',kind:'item_frame',template:null},{name:'Armor Stand',file:'templates/armor_stand/test_template_armorstand.nbt',preview:'templates_preview/armor_stand/test_template_armorstand.gif',kind:'armor_stand',template:null}];
const isDev=location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.protocol==='file:';
function renderTemplates(){let el=$('templateCards');el.innerHTML=templates.map((x,i)=>`<button class="template ${i===0?'selected':''}" data-i="${i}"><img src="${x.preview}" alt="" onerror="this.style.display='none'"><strong>${x.name}</strong><small>${x.template?`${x.template.kind==='armor_stand'?'Armor Stand':'Item Frame'} · ${x.template.size.join(' × ')} · ${x.template.slots.length} slots`:'loading...'}</small></button>`).join('');el.querySelectorAll('.template').forEach(b=>b.onclick=()=>{el.querySelectorAll('.template').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');let selected=templates[Number(b.dataset.i)];if(selected.template){template=selected.template;showTemplate()}})}
function showTemplate(){let normal=template.slots?.filter(x=>(x.id||x.nbt?.id)==='minecraft:item_frame').length??template.entities.filter(x=>(x.id||x.nbt?.id)==='minecraft:item_frame').length;$('templateInfo').textContent=`${template.kind==='armor_stand'?'Armor Stand':'Item Frame'} template · Size: ${template.size.join(' × ')} · Entities: ${template.entities.length} · Generator slots: ${template.slots?.length||normal} · Decorative: ${template.decorative||0}`;updateSummary()}
function showPack(){let supported=pack.variants.filter(v=>v.supported);$('packStats').classList.remove('hidden');$('packStats').innerHTML=`<div><strong>${pack.definitions.length}</strong><small>Definitions</small></div><div><strong>${pack.variants.length}</strong><small>Item variants</small></div><div><strong>${pack.warnings.length}</strong><small>Warnings</small></div>`;report={generatorVersion:'1.0.0',target:'Java 1.21.5',definitions:pack.definitions.length,variants:pack.variants.length,warnings:pack.warnings,properties:pack.properties};renderVariants();updateSummary()}
function renderVariants(){let q=$('search').value.toLowerCase(),v=pack.variants.filter(x=>`${x.baseItem} ${x.model} ${x.sourceDefinition}`.toLowerCase().includes(q));$('variants').innerHTML=v.slice(0,300).map((x,i)=>`<article class="variant"><b>#${i+1}</b> ${x.baseItem}<br><code>${x.model}</code><pre>${JSON.stringify(x.components||{},null,2)}</pre></article>`).join('')||'<p class="muted">No matching variants.</p>'}
function updateSummary(){if(!pack)return;$('generate').disabled=!template.slots?.length;let s=template.slots?.length||0,n=pack.variants.length,count=Math.ceil(n/Math.max(1,s));$('summary').innerHTML=`<b>${n.toLocaleString()}</b> variants · <b>${s}</b> slots · <b>${count.toLocaleString()}</b> sections · sequential south layout · Java Edition 1.21.5`}
async function loadPack(file){try{$('packStats').innerHTML='<p class="muted">Reading resource pack...</p>';$('packStats').classList.remove('hidden');pack=await analysePack(await file.arrayBuffer());showPack()}catch(e){$('packStats').innerHTML=`<p class="muted">${e.message}</p>`}}
async function parseTemplateBytes(bytes,kind='item_frame'){try{return readTemplate(bytes,kind)}catch(_){return readTemplate(await gunzip(bytes),kind)}}
async function loadTemplate(file){try{const bytes=new Uint8Array(await file.arrayBuffer());template=await parseTemplateBytes(bytes,'item_frame');if(!template.slots.length&&template.entities.some(entity=>(entity.id||entity.nbt?.id)==='minecraft:armor_stand'))template=await parseTemplateBytes(bytes,'armor_stand');showTemplate()}catch(e){$('templateInfo').textContent='Template error: '+e.message}}
async function loadDefaultTemplates(){for(const option of templates){try{let response=await fetch(option.file);if(!response.ok)throw Error(`${option.file} is not available`);option.template=await parseTemplateBytes(new Uint8Array(await response.arrayBuffer()),option.kind)}catch(e){console.warn(e.message)}}if(templates[0].template)template=templates[0].template;renderTemplates();showTemplate()}
async function loadCategories(){try{let response=await fetch('config/item-categories.json');if(response.ok)categoryConfig=await response.json()}catch(e){console.warn('Category config unavailable',e)}}
function matchesCategory(item,category){return category.items.includes(item)||category.patterns.some(pattern=>new RegExp(`^${pattern.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*')}$`).test(item))}
function buildGroups(variants){if(!categoryConfig)return[{id:'all',title:'All',variants}];let remaining=[...variants],groups=[];for(const category of categoryConfig.categories){let selected=category.id==='fallback'?remaining:remaining.filter(variant=>matchesCategory(variant.baseItem,category));if(category.id!=='fallback')remaining=remaining.filter(variant=>!selected.includes(variant));if(selected.length)groups.push({id:category.id,title:category.title,variants:selected})}return groups.length?groups:[{id:'fallback',title:'Fallback',variants}]} 
async function loadTestPack(){let status=$('devStatus');status.textContent='Loading test_rp/TreeCube.zip...';try{let r=await fetch('test_rp/TreeCube.zip');if(!r.ok)throw Error('test_rp/TreeCube.zip was not found');let b=await r.arrayBuffer();pack=await analysePack(b);showPack();status.textContent=`Loaded test fixture: ${pack.variants.length} variants`;}catch(e){status.textContent='Test fixture unavailable: '+e.message}}
function download(data,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/zip'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
renderTemplates();showTemplate();loadDefaultTemplates();loadCategories();if(isDev){$('devTools').classList.remove('hidden');$('loadTestPack').onclick=loadTestPack;if(location.protocol!=='file:')loadTestPack()}$('packInput').onchange=e=>e.target.files[0]&&loadPack(e.target.files[0]);$('templateInput').onchange=e=>e.target.files[0]&&loadTemplate(e.target.files[0]);$('search').oninput=()=>pack&&renderVariants();$('packDrop').ondragover=e=>e.preventDefault();$('packDrop').ondrop=e=>{e.preventDefault();let f=e.dataTransfer.files[0];if(f)loadPack(f)};
 $('generate').onclick=async()=>{if(!pack||!template.slots?.length)return;let p=$('progress'),bar=$('progressBar'),txt=$('progressText'),pct=$('progressPct');p.classList.remove('hidden');$('generate').disabled=true;try{let settings={layout:'line',perRow:1,gap:0,groups:buildGroups(pack.variants),name:$('worldName').value.replace(/[\\/:*?"<>|]/g,' ').trim()||'Custom Item Gallery'};let result=await generateWorld(template,pack.variants,settings,(n,t)=>{bar.style.width=(n*100)+'%';pct.textContent=Math.round(n*100)+'%';txt.textContent=t});download(result.zip,(settings.name.replace(/\s+/g,'_')||'CustomItemGallery')+'.zip');report.template={size:template.size,kind:template.kind,entities:template.entities.length,slots:template.slots.length};report.world={...settings,groups:settings.groups.map(group=>({id:group.id,title:group.title,items:group.variants.length}))};report.sections=result.sections}catch(e){txt.textContent='Generation failed: '+e.message;console.error(e)}finally{$('generate').disabled=false}};
$('debug').onclick=()=>download(new TextEncoder().encode(JSON.stringify({...report,generatedAt:new Date().toISOString()},null,2)),'debug-report.json');
$('downloadVariants').onclick=()=>{if(!pack)return;const variants=pack.variants.map(({fingerprint,...variant})=>variant);download(new TextEncoder().encode(JSON.stringify({target:'Minecraft Java Edition 1.21.5',definitions:pack.definitions.length,variants},null,2)),'detected-variants.json')};
$('downloadProperties').onclick=()=>{if(!pack)return;download(new TextEncoder().encode(JSON.stringify({target:'Minecraft Java Edition 1.21.5',observedProperties:pack.properties||[],knownProperties:[{property:'minecraft:custom_model_data',component:'minecraft:custom_model_data',status:'supported'},{property:'minecraft:custom_name',component:'minecraft:custom_name',status:'supported'},{property:'minecraft:trim_material',component:'minecraft:trim.material',status:'supported'},{property:'minecraft:trim_pattern',component:'minecraft:trim.pattern',status:'supported'},{property:'minecraft:display_context',status:'context-dependent'},{property:'minecraft:damage',status:'not yet resolved'},{property:'minecraft:charge_type',status:'not yet resolved'},{property:'minecraft:bundle_contents',status:'not yet resolved'}]},null,2)),'item-model-properties.json')};
