import {analysePack} from './resourcepack.js';import {builtinTemplate,readTemplate,isPavilionFile} from './template.js';import {gunzip} from './nbt.js';import {generateWorld} from './world.js';
const $=id=>document.getElementById(id);let pack=null,template=builtinTemplate(),selectedTemplate=null,categoryConfig=null,pavilionConfig={spacing:200,templates:{}},report={},language=localStorage.getItem('gallery-language')||'ru',pavilionTemplates=[];
const tr=(ru,en)=>language==='ru'?ru:en;
function applyLanguage(){document.documentElement.lang=language;$('languageToggle').textContent=language==='ru'?'EN':'RU';const headers=document.querySelectorAll('.panel-header');['1 · Ресурс-пак','2 · Шаблон','3 · Мир'].map((ru,i)=>headers[i].textContent=tr(ru,['1 · Resource Pack','2 · Template','3 · World'][i]));$('packDrop').querySelector('strong').textContent=tr('Перетащите ZIP ресурс-пака','Drop Resource Pack ZIP');$('packDrop').querySelector('.drop-zone-subtext').textContent=tr('или нажмите, чтобы выбрать локальный файл','or click to select a local file');$('packDrop').querySelector('small').textContent=tr('ZIP обрабатывается прямо в браузере','ZIP files are processed in your browser');$('loadTestPack').textContent=tr('Загрузить тестовый pack','Load test pack');$('templateInput').parentElement.lastChild.textContent=tr('＋ Загрузить свой template.nbt','＋ Upload custom template.nbt');$('templateInfo').textContent=tr('Загрузка шаблонов...','Loading templates...');$('worldName').parentElement.firstChild.textContent=tr('Название мира','World name');$('summary').textContent=tr('Загрузите ресурс-пак для расчёта галереи.','Load a resource pack to calculate the gallery.');$('generate').textContent=tr('СОЗДАТЬ ZIP МИРА','GENERATE WORLD ZIP');document.querySelector('.eyebrow').textContent=tr('РЕЗУЛЬТАТ АНАЛИЗА','ANALYSIS RESULT');document.querySelector('.workspace h1').textContent=tr('Найденные варианты','Detected variants');document.querySelector('.workspace-head p').textContent=tr('Обработанные Item Model Definitions и компоненты ItemStack.','Resolved Item Model Definitions and generated ItemStack components.');$('downloadVariants').textContent=tr('Скачать варианты','Download variants');$('downloadProperties').textContent=tr('Properties JSON','Properties JSON');$('debug').textContent=tr('Отчёт отладки','Debug report');$('search').placeholder=tr('Поиск namespace, предмета или модели...','Search namespace, item, model...');$('variants').innerHTML=`<p class="muted">${tr('Ресурс-пак ещё не проанализирован.','No resource pack analysed yet.')}</p>`;document.querySelector('footer').innerHTML=tr('Всё обрабатывается локально.<br>Ресурс-пак никуда не загружается.','Everything is processed locally.<br>Your resource pack is never uploaded.');if(pack)showPack();showTemplate()}
let templates=[{file:'templates/item_frame/test.nbt',preview:'templates_preview/item_frame/test.gif',kind:'item_frame',template:null,pavilion:false},{file:'templates/item_frame/ksepsp.nbt',preview:'templates_preview/item_frame/ksepsp.gif',kind:'item_frame',template:null,pavilion:false},{file:'templates/armor_stand/test.nbt',preview:'templates_preview/armor_stand/test.gif',kind:'armor_stand',template:null,pavilion:false}];
function templateName(file){let name=file.split('/').pop().replace(/\.nbt$/i,'').replace(/_template(?:_armorstand)?$/i,'');if(!name&&/template\.nbt$/i.test(file))name='template';return name.split(/[_-]+/).filter(Boolean).map(word=>word[0].toUpperCase()+word.slice(1).toLowerCase()).join(' ')}
function templateLabel(option){return `${option.kind==='armor_stand'?tr('Стойка для брони','Armor Stand'):tr('Рамка предмета','Item Frame')} · ${templateName(option.file)}`}
const isDev=location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.protocol==='file:';
function pavilionFor(option){if(!option)return null;let expected=option.file.replace(/\.nbt$/i,'_pavilion.nbt').toLowerCase();return pavilionTemplates.find(x=>x.file.toLowerCase()===expected)||null}
function templateOptions(){let single=document.querySelector('input[name="layoutMode"]:checked')?.value==='single';return templates.filter(x=>!x.pavilion&&(single||pavilionFor(x)))}
function renderTemplates(){let el=$('templateCards'),options=templateOptions();if(!options.includes(selectedTemplate))selectedTemplate=options[0]||null;el.innerHTML=options.map((x,i)=>`<button class="template ${x===selectedTemplate?'selected':''}" data-i="${i}"><img src="${x.preview||''}" alt="" onerror="this.style.display='none'"><strong>${templateLabel(x)}</strong><small>${x.template?`${x.template.size.join(' × ')} · ${x.template.slots.length} ${tr('слотов','slots')}`:tr('загрузка...','loading...')}</small></button>`).join('')||`<p class="muted">${tr('Нет подходящих пар template + pavilion.','No matching template + pavilion pairs.')}</p>`;el.querySelectorAll('.template').forEach(b=>b.onclick=()=>{el.querySelectorAll('.template').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedTemplate=options[Number(b.dataset.i)];template=selectedTemplate.template;showTemplate()});updateModeVisibility()}
function showTemplate(){let normal=template.slots?.filter(x=>(x.id||x.nbt?.id)==='minecraft:item_frame').length??template.entities.filter(x=>(x.id||x.nbt?.id)==='minecraft:item_frame').length;$('templateInfo').textContent=`${template.kind==='armor_stand'?tr('Стойка для брони','Armor Stand'):tr('Рамка предмета','Item Frame')} · ${tr('Размер','Size')}: ${template.size.join(' × ')} · ${tr('Сущностей','Entities')}: ${template.entities.length} · ${tr('Слотов','Slots')}: ${template.slots?.length||normal} · ${tr('Декоративных','Decorative')}: ${template.decorative||0}`;updateSummary()}
function showPack(){let supported=pack.variants.filter(v=>v.supported);$('packStats').classList.remove('hidden');$('packStats').innerHTML=`<div><strong>${pack.definitions.length}</strong><small>${tr('Определения','Definitions')}</small></div><div><strong>${pack.variants.length}</strong><small>${tr('Варианты','Item variants')}</small></div><div><strong>${pack.warnings.length}</strong><small>${tr('Предупреждения','Warnings')}</small></div>`;report={generatorVersion:'1.0.0',target:'Java 1.21.5',definitions:pack.definitions.length,variants:pack.variants.length,warnings:pack.warnings,properties:pack.properties};renderVariants();updateSummary()}
function renderVariants(){let q=$('search').value.toLowerCase(),v=pack.variants.filter(x=>`${x.baseItem} ${x.model} ${x.sourceDefinition}`.toLowerCase().includes(q));$('variants').innerHTML=v.slice(0,300).map((x,i)=>`<article class="variant"><b>#${i+1}</b> ${x.baseItem}<br><code>${x.model}</code><pre>${JSON.stringify(x.components||{},null,2)}</pre></article>`).join('')||`<p class="muted">${tr('Нет подходящих вариантов.','No matching variants.')}</p>`}
function updateSummary(){if(!pack)return;updateModeVisibility();let s=template.slots?.length||0,n=pack.variants.length,count=Math.ceil(n/Math.max(1,s));$('summary').innerHTML=`<b>${n.toLocaleString()}</b> ${tr('вариантов','variants')} · <b>${s}</b> ${tr('слотов','slots')} · <b>${count.toLocaleString()}</b> ${tr('секций','sections')} · ${tr('режим зависит от выбранной раскладки','layout depends on selected mode')} · Java Edition 1.21.5`}
async function loadPack(file){try{$('packStats').innerHTML=`<p class="muted">${tr('Чтение ресурс-пака...','Reading resource pack...')}</p>`;$('packStats').classList.remove('hidden');pack=await analysePack(await file.arrayBuffer());showPack()}catch(e){$('packStats').innerHTML=`<p class="muted">${e.message}</p>`}}
async function parseTemplateBytes(bytes,kind='item_frame'){try{return readTemplate(bytes,kind)}catch(_){return readTemplate(await gunzip(bytes),kind)}}
function updateModeVisibility(){let single=document.querySelector('input[name="layoutMode"]:checked')?.value==='single';$('customTemplateUpload').classList.toggle('hidden',!single);$('generate').disabled=!pack||!selectedTemplate||!template.slots?.length}
async function loadTemplate(file){try{if(document.querySelector('input[name="layoutMode"]:checked')?.value!=='single'){ $('templateInfo').textContent=tr('Загрузка custom template доступна только в Single Corridor.','Custom template upload is available only in Single Corridor.');return}if(isPavilionFile(file.name)){ $('templateInfo').textContent=tr('Выберите обычный corridor template, без суффикса _pavilion.','Choose a regular corridor template without the _pavilion suffix.');return}const bytes=new Uint8Array(await file.arrayBuffer());let kind='item_frame',loaded=await parseTemplateBytes(bytes,kind);if(!loaded.slots.length&&loaded.entities.some(entity=>(entity.id||entity.nbt?.id)==='minecraft:armor_stand')){kind='armor_stand';loaded=await parseTemplateBytes(bytes,kind)}let option={file:file.name,preview:'',kind,template:loaded,pavilion:false};templates.push(option);selectedTemplate=option;template=loaded;renderTemplates();showTemplate()}catch(e){$('templateInfo').textContent='Ошибка шаблона: '+e.message}}
async function loadDefaultTemplates(){for(const option of [...templates,...pavilionTemplates]){try{let response=await fetch(option.file);if(!response.ok)throw Error(`${option.file} is not available`);option.template=await parseTemplateBytes(new Uint8Array(await response.arrayBuffer()),option.kind)}catch(e){console.warn(e.message)}}renderTemplates();if(selectedTemplate?.template){template=selectedTemplate.template;showTemplate()}}
async function loadTemplateManifest(){try{let response=await fetch('config/templates.json');if(response.ok){let manifest=await response.json();templates=manifest.templates.map(x=>({...x,template:null,pavilion:false}));pavilionTemplates=manifest.pavilions.map(x=>({...x,template:null,pavilion:true}))}}catch(e){console.warn('Template manifest unavailable',e)}try{let response=await fetch('config/pavilions.json');if(response.ok)pavilionConfig=await response.json()}catch(e){console.warn('Pavilion config unavailable',e)}}
async function loadCategories(){try{let response=await fetch('config/item-categories.json');if(response.ok)categoryConfig=await response.json()}catch(e){console.warn('Category config unavailable',e)}}
function matchesCategory(item,category){return category.items.includes(item)||category.patterns.some(pattern=>new RegExp(`^${pattern.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*')}$`).test(item))}
function buildGroups(variants){if(!categoryConfig)return[{id:'all',title:'Все предметы',variants}];const titles={food:'Еда',weapons:'Оружие',tools:'Инструменты',armor:'Броня',potions:'Зелья',blocks:'Блоки',materials:'Материалы',fallback:'Остальное'};let remaining=[...variants],groups=[];for(const category of categoryConfig.categories){let selected=category.id==='fallback'?remaining:remaining.filter(variant=>matchesCategory(variant.baseItem,category));if(category.id!=='fallback')remaining=remaining.filter(variant=>!selected.includes(variant));if(selected.length)groups.push({id:category.id,title:titles[category.id]||category.title,variants:selected})}return groups.length?groups:[{id:'fallback',title:'Остальное',variants}]} 
async function loadTestPack(){let status=$('devStatus');status.textContent='Загрузка test_rp/TreeCube.zip...';try{let r=await fetch('test_rp/TreeCube.zip');if(!r.ok)throw Error('test_rp/TreeCube.zip не найден');let b=await r.arrayBuffer();pack=await analysePack(b);showPack();status.textContent=`Тестовый fixture загружен: ${pack.variants.length} вариантов`;}catch(e){status.textContent='Тестовый fixture недоступен: '+e.message}}
function download(data,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/zip'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('pavilionTemplate')?.remove();document.querySelectorAll('input[name="layoutMode"]').forEach(input=>input.onchange=()=>{renderTemplates();if(selectedTemplate?.template){template=selectedTemplate.template;showTemplate()}});renderTemplates();showTemplate();loadTemplateManifest().then(loadDefaultTemplates);loadCategories();if(isDev){$('devTools').classList.remove('hidden');$('loadTestPack').onclick=loadTestPack;if(location.protocol!=='file:')loadTestPack()}$('packInput').onchange=e=>e.target.files[0]&&loadPack(e.target.files[0]);$('templateInput').onchange=e=>e.target.files[0]&&loadTemplate(e.target.files[0]);$('search').oninput=()=>pack&&renderVariants();$('packDrop').ondragover=e=>e.preventDefault();$('packDrop').ondrop=e=>{e.preventDefault();let f=e.dataTransfer.files[0];if(f)loadPack(f)};
  $('generate').onclick=async()=>{if(!pack||!template.slots?.length)return;let p=$('progress'),bar=$('progressBar'),txt=$('progressText'),pct=$('progressPct');p.classList.remove('hidden');$('generate').disabled=true;try{let mode=document.querySelector('input[name="layoutMode"]:checked')?.value||'pavilions',groups=mode==='single'?[{id:'all',title:'Все предметы',variants:pack.variants}]:buildGroups(pack.variants),pavilion=pavilionFor(selectedTemplate),settings={mode,groups,name:$('worldName').value.replace(/[\\/:*?"<>|]/g,' ').trim()||'Custom Item Gallery',corridorTemplate:template,pavilion,pavilionKey:pavilion?.file,pavilionConfig,pavilionSpacing:pavilionConfig.spacing};let result=await generateWorld(template,pack.variants,settings,(n,t)=>{bar.style.width=(n*100)+'%';pct.textContent=Math.round(n*100)+'%';txt.textContent=t});download(result.zip,(settings.name.replace(/\s+/g,'_')||'CustomItemGallery')+'.zip');report.template={size:template.size,kind:template.kind,entities:template.entities.length,slots:template.slots.length};report.world={...settings,groups:settings.groups.map(group=>({id:group.id,title:group.title,items:group.variants.length}))};report.sections=result.sections}catch(e){txt.textContent='Generation failed: '+e.message;console.error(e)}finally{updateModeVisibility()}};
$('debug').onclick=()=>download(new TextEncoder().encode(JSON.stringify({...report,generatedAt:new Date().toISOString()},null,2)),'debug-report.json');
$('downloadVariants').onclick=()=>{if(!pack)return;const variants=pack.variants.map(({fingerprint,...variant})=>variant);download(new TextEncoder().encode(JSON.stringify({target:'Minecraft Java Edition 1.21.5',definitions:pack.definitions.length,variants},null,2)),'detected-variants.json')};
$('downloadProperties').onclick=()=>{if(!pack)return;download(new TextEncoder().encode(JSON.stringify({target:'Minecraft Java Edition 1.21.5',observedProperties:pack.properties||[],knownProperties:[{property:'minecraft:custom_model_data',component:'minecraft:custom_model_data',status:'supported'},{property:'minecraft:custom_name',component:'minecraft:custom_name',status:'supported'},{property:'minecraft:trim_material',component:'minecraft:trim.material',status:'supported'},{property:'minecraft:trim_pattern',component:'minecraft:trim.pattern',status:'supported'},{property:'minecraft:display_context',status:'context-dependent'},{property:'minecraft:damage',status:'not yet resolved'},{property:'minecraft:charge_type',status:'not yet resolved'},{property:'minecraft:bundle_contents',status:'not yet resolved'}]},null,2)),'item-model-properties.json')};
$('languageToggle').onclick=()=>{language=language==='ru'?'en':'ru';localStorage.setItem('gallery-language',language);applyLanguage();renderTemplates()};applyLanguage();renderTemplates();
