const T={end:0,byte:1,short:2,int:3,long:4,float:5,double:6,byteArray:7,string:8,list:9,compound:10,intArray:11,longArray:12};
const listTag=(type,value)=>({__listType:type,value});
class Reader{constructor(a){this.a=a;this.v=new DataView(a.buffer,a.byteOffset,a.byteLength);this.p=0}u8(){return this.a[this.p++]} i8(){return this.v.getInt8(this.p++)} u16(){let x=this.v.getUint16(this.p);this.p+=2;return x} i16(){let x=this.v.getInt16(this.p);this.p+=2;return x} i32(){let x=this.v.getInt32(this.p);this.p+=4;return x} i64(){let x=this.v.getBigInt64(this.p);this.p+=8;return x} f32(){let x=this.v.getFloat32(this.p);this.p+=4;return x} f64(){let x=this.v.getFloat64(this.p);this.p+=8;return x} str(){let n=this.u16(),s=new TextDecoder().decode(this.a.slice(this.p,this.p+n));this.p+=n;return s} tag(t,name=''){if(t===1)return this.i8();if(t===2)return this.i16();if(t===3)return this.i32();if(t===4)return this.i64();if(t===5)return this.f32();if(t===6)return this.f64();if(t===7){let n=this.i32();return Array.from(this.a.slice(this.p,this.p+=n));}if(t===8)return this.str();if(t===9){let k=this.u8(),n=this.i32(),v=[];for(let i=0;i<n;i++)v.push(this.tag(k));return v}if(t===10){let o={};for(;;){let k=this.u8();if(!k)break;let n=this.str();o[n]=this.tag(k,n)}return o}if(t===11){let n=this.i32(),v=[];for(let i=0;i<n;i++)v.push(this.i32());return v}if(t===12){let n=this.i32(),v=[];for(let i=0;i<n;i++)v.push(this.i64());return v}throw Error('Unknown NBT tag '+t)}root(){let t=this.u8();if(t!==10)throw Error('NBT root is not compound');let name=this.str();return {type:10,name,value:this.tag(10,name)}}}
class Writer{constructor(){this.a=[]}byte(x){this.a.push(x&255)}bytes(a){this.a.push(...a)}u16(x){this.bytes([(x>>8)&255,x&255])}i16(x){this.bytes([(x>>8)&255,x&255])}i32(x){this.bytes([(x>>24)&255,(x>>16)&255,(x>>8)&255,x&255])}i64(x){let b=new ArrayBuffer(8);new DataView(b).setBigInt64(0,BigInt(x));this.bytes(new Uint8Array(b))}f32(x){let b=new ArrayBuffer(4);new DataView(b).setFloat32(0,x);this.bytes(new Uint8Array(b))}f64(x){let b=new ArrayBuffer(8);new DataView(b).setFloat64(0,x);this.bytes(new Uint8Array(b))}str(s){let b=new TextEncoder().encode(s);this.u16(b.length);this.bytes(b)}type(v){if(v?.__nbtType)return v.__nbtType;if(v?.__listType)return 9;if(typeof v==='string')return 8;if(typeof v==='bigint')return 4;if(typeof v==='number')return Number.isInteger(v)?3:6;if(Array.isArray(v))return 9;if(v&&typeof v==='object')return 10;return 1}tag(t,n,v,root=false){if(!root){this.byte(t);this.str(n)}if(v?.__nbtType)v=v.value;if(t===7){this.i32(v.length);this.bytes(v);return}if(t===11){this.i32(v.length);v.forEach(x=>this.i32(x));return}if(t===12){this.i32(v.length);v.forEach(x=>this.i64(x));return}if(t===1)this.byte(v);else if(t===2)this.i16(v);else if(t===3)this.i32(v);else if(t===4)this.i64(v);else if(t===5)this.f32(v);else if(t===6)this.f64(v);else if(t===8)this.str(v);else if(t===9){let k=v?.__listType??(v.length?this.type(v[0]):1),values=v?.__listType?v.value:v;this.byte(k);this.i32(values.length);for(const x of values)this.tag(k,'',x,true)}else if(t===10){for(const [k,x] of Object.entries(v))this.tag(this.type(x),k,x);this.byte(0)}else throw Error('Writer does not infer array tags')}root(o){this.byte(10);this.u16(0);this.tag(10,'',o,true);return new Uint8Array(this.a)}}
export function parseNBT(data){return new Reader(data instanceof Uint8Array?data:new Uint8Array(data)).root().value}
export function writeNBT(value){return new Writer().root(value)}
export async function gunzip(data){return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer())}
export async function gzip(data){return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer())}
export {T,listTag};
